/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --types --shadows enemy.glb 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'attack01' | 'attack02' | 'attack02.001' | 'attack02.002' | 'knockback' | 'parry-01' | 'parry-02' | 'stance'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Sphere001: THREE.SkinnedMesh
    Sphere001_1: THREE.SkinnedMesh
    body_1: THREE.SkinnedMesh
    Sphere002: THREE.SkinnedMesh
    Sphere002_1: THREE.SkinnedMesh
    body: THREE.Bone
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/enemy.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.body} />
          <group name="arm-sword">
            <skinnedMesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.002']} skeleton={nodes.Sphere001.skeleton} />
            <skinnedMesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials['Material.001']} skeleton={nodes.Sphere001_1.skeleton} />
          </group>
          <skinnedMesh name="body_1" geometry={nodes.body_1.geometry} material={materials['Material.002']} skeleton={nodes.body_1.skeleton} />
          <group name="canon">
            <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.002']} skeleton={nodes.Sphere002.skeleton} />
            <skinnedMesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials['Material.003']} skeleton={nodes.Sphere002_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/enemy.glb')
